#!/bin/bash

pushd `dirname $0` > /dev/null

function usage() {
	echo "Usage: $0 [build|app]"
	exit 1
}

function error() {
	echo "Error: $1"
	exit 1
}

[ $# -eq 0 ] && usage

if [ $1 == "build" ]; then
	echo "Running Go-Lint..."
	golint main.go
	echo "Building project..."
	go build main.go || error "Unable to build project"
	echo "Done... try executing using: $0 app"
fi

if [ $1 == "app" ]; then
	[ ! -x main ] && error "Build project first"
        ./main
fi
